# - name: Link Nginx to the shared folder
#   replace: dest=/etc/nginx/nginx.conf regexp='\/usr\/share\/nginx\/html' replace='/web'
#
# - name: Ensure Nginx running
#   service: name=nginx state=started enabled=yes

- name: Create folders
  file: path={{ item.path }} mode={{ item.mode }} state=directory owner=root group=root
  with_items:
    - { path: "/etc/nginx/sites-available", mode: 755 }
    - { path: "/etc/nginx/sites-enabled", mode: 755 }

- name: Copy new config file.
  template:
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy new virtual hosts file.
  template:
    src=wordpress
    dest=/etc/nginx/sites-available/wordpress

- name: Copy index test page
  template:
    src=index.php
    dest=/usr/share/nginx/html/index.php

- name: Disable default virtual hosts file.
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: Give permissions to homedir
  seboolean: 
    name: httpd_enable_homedirs
    state: yes
    persistent: yes

- name: Enable new virtual hosts file.
  file:
    src=/etc/nginx/sites-available/wordpress
    dest=/etc/nginx/sites-enabled/wordpress
    state=link
  notify:
    - restart nginx
