- set_fact: role_name=nginx
  become: yes
  become_user: root
##################################################
### Install, configure and secure webserver
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: secure.yml
