- name: Allow public to use http service
  firewalld:  
    service: http
    permanent: true
    state: enabled
    zone: public

- name: Allow public to port 80 in firewall
  firewalld:  
    port: 80/tcp 
    permanent: true
    state: enabled
    zone: public

- name: Allow public to use https service
  firewalld:  
    service: https
    permanent: true
    state: enabled
    zone: public

- name: Allow public to port 443 in firewall
  firewalld: 
    port: 443/tcp 
    permanent: true
    state: enabled
    zone: public

- name: Reload firewall
  shell: firewall-cmd --reload

- name: Flush iptables
  shell: iptables -F
