- set_fact: role_name=basics
  become: yes
  become_user: root
##################################################
### Basic system packages and firewall config
- name: Start firewalld and enable at start
  service: name=firewalld state=started enabled=yes

- name: Update Yum
  yum: 
    name: '*' 
    state: latest

- name: Install basic packages
  yum: 
    name:
      - yum-utils
      - vim
      - git
      - curl
      - wget
      - vim
      - man
      - zip
      - unzip
      - epel-release
